"""empty message

Revision ID: 5a90fde5ab86
Revises: d04fd31e6ba7
Create Date: 2019-06-07 14:47:14.206700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a90fde5ab86'
down_revision = 'd04fd31e6ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipo', sa.Column('sn_autostartMQTT', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipo', 'sn_autostartMQTT')
    # ### end Alembic commands ###
