"""empty message

Revision ID: d04fd31e6ba7
Revises: 
Create Date: 2019-06-04 14:25:20.052900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04fd31e6ba7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo',
    sa.Column('mac_raspberry', sa.String(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('ip_equipo', sa.String(), nullable=True),
    sa.Column('nombre_raspberry', sa.String(), nullable=False),
    sa.Column('tiempo_ver_nuevos_hilos', sa.Float(), nullable=True),
    sa.Column('tiempo_sincronizacion', sa.Float(), nullable=True),
    sa.Column('send_to', sa.String(), nullable=True),
    sa.Column('monitoreo_name_process', sa.String(), nullable=True),
    sa.Column('server_mqtt_name_process', sa.String(), nullable=True),
    sa.Column('api_name_process', sa.String(), nullable=True),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mac_raspberry', 'id_equipo')
    )
    op.create_table('registro',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('guid_sensor', sa.String(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('fe_registrado', sa.String(), nullable=True),
    sa.Column('canal0', sa.Float(), nullable=True),
    sa.Column('canal1', sa.Float(), nullable=True),
    sa.Column('canal2', sa.Float(), nullable=True),
    sa.Column('canal3', sa.Float(), nullable=True),
    sa.Column('canal4', sa.Float(), nullable=True),
    sa.Column('canal5', sa.Float(), nullable=True),
    sa.Column('canal6', sa.Float(), nullable=True),
    sa.Column('canal7', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_table('serverMQTT',
    sa.Column('id_server', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('de_comentario', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_server')
    )
    op.create_table('server_secundario',
    sa.Column('id_server', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_server')
    )
    op.create_table('sensor',
    sa.Column('id_sensor', sa.Integer(), nullable=False),
    sa.Column('guid_sensor', sa.String(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('codigo_sensor', sa.String(), nullable=False),
    sa.Column('nombre_sensor', sa.String(), nullable=False),
    sa.Column('pin_sensor', sa.Integer(), nullable=True),
    sa.Column('estado_sensor', sa.Boolean(), nullable=False),
    sa.Column('tiempo', sa.Integer(), nullable=True),
    sa.Column('variacion', sa.Integer(), nullable=True),
    sa.Column('tipo_actualizacion', sa.String(), nullable=False),
    sa.Column('val_max', sa.Integer(), nullable=True),
    sa.Column('val_min', sa.Integer(), nullable=True),
    sa.Column('actuador', sa.Boolean(), nullable=False),
    sa.Column('ti_comportamiento', sa.Integer(), nullable=True),
    sa.Column('canales', sa.String(), nullable=True),
    sa.Column('descripcion_serie', sa.String(), nullable=True),
    sa.Column('ti_conexion', sa.Integer(), nullable=True),
    sa.Column('topico_suscripto', sa.String(), nullable=True),
    sa.Column('ti_sensor', sa.String(), nullable=True),
    sa.Column('server_mqtt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_mqtt_id'], ['serverMQTT.id_server'], ),
    sa.PrimaryKeyConstraint('id_sensor', 'id_modulo')
    )
    op.create_table('registro_interno',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('guid_sensor', sa.String(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('fe_registrado', sa.String(), nullable=True),
    sa.Column('canal0', sa.Float(), nullable=True),
    sa.Column('canal1', sa.Float(), nullable=True),
    sa.Column('canal2', sa.Float(), nullable=True),
    sa.Column('canal3', sa.Float(), nullable=True),
    sa.Column('canal4', sa.Float(), nullable=True),
    sa.Column('canal5', sa.Float(), nullable=True),
    sa.Column('canal6', sa.Float(), nullable=True),
    sa.Column('canal7', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['guid_sensor'], ['sensor.guid_sensor'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_interno')
    op.drop_table('sensor')
    op.drop_table('server_secundario')
    op.drop_table('serverMQTT')
    op.drop_table('registro')
    op.drop_table('equipo')
    # ### end Alembic commands ###
